version: '3.9'

services:
  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node-server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/?directConnection=true
    env_file:
      - .env
    depends_on:
      - mongodb

  react-client:
    build:
      context: ./react-client
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./react-client:/usr/src/app
    ports:
      - "4000:4000"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
